title: "Programming with Rehman Blog"
description: "A blog for sharing programming knowledge."
baseurl: ""  # Leave this empty for now
url: "https://programmingwithrehman.github.io/blog"  # Your GitHub Pages URL

# Permalink configuration
permalink: /:title/
