title: My Blog
description: A blog about programming and freelancing
baseurl: "" # Use this if your site is a project page
url: "https://programmingwithrehman.github.io"
theme: minima # or any other theme you prefer
