title: "Programming with Rehman Blog"
description: "A blog for sharing programming knowledge."
baseurl: "" # Leave this empty
url: "https://programmingwithrehman.github.io/blog" # Replace with your site URL

# Remove date from URLs
permalink: /:title/
